import type { ItemName, MapArea, Profession, ShopItem, SkillTemplate } from "./types";

export const SKILL_TEMPLATES: SkillTemplate[] = [
  {
    id: "warrior_attack_slash",
    name: "攻杀剑术",
    bookName: "攻杀剑术技能书",
    profession: "战士",
    unlockLevel: 1,
    kind: "attack",
    manaCost: 12,
    cooldown: 1,
    basePower: 34,
    scaling: 1.32,
    duration: 0,
    description: "蓄力后劈出一记重斩，剑锋贴地掠过，专克正面目标。",
  },
  {
    id: "warrior_half_moon",
    name: "半月弯刀",
    bookName: "半月弯刀技能书",
    profession: "战士",
    unlockLevel: 7,
    kind: "attack",
    manaCost: 18,
    cooldown: 2,
    basePower: 42,
    scaling: 1.15,
    duration: 0,
    description: "刀光横扫如半月，连斩一线敌影，压制力极强。",
  },
  {
    id: "warrior_charge",
    name: "野蛮冲撞",
    bookName: "野蛮冲撞技能书",
    profession: "战士",
    unlockLevel: 14,
    kind: "attack",
    manaCost: 16,
    cooldown: 2,
    basePower: 38,
    scaling: 1.08,
    duration: 0,
    description: "低身突进撞开敌势，重心被打乱后再补上一记狠刺。",
  },
  {
    id: "warrior_fire_sword",
    name: "烈火剑法",
    bookName: "烈火剑法技能书",
    profession: "战士",
    unlockLevel: 22,
    kind: "attack",
    manaCost: 28,
    cooldown: 3,
    basePower: 80,
    scaling: 1.52,
    duration: 0,
    description: "烈焰缠刃，蓄势一击爆发炽热剑压，往往一击定胜负。",
  },
  {
    id: "mage_fireball",
    name: "火球术",
    bookName: "火球术技能书",
    profession: "法师",
    unlockLevel: 1,
    kind: "attack",
    manaCost: 16,
    cooldown: 1,
    basePower: 40,
    scaling: 1.22,
    duration: 0,
    description: "掌心聚焰成球，火焰拖尾撕开空气，精准轰向敌人要害。",
  },
  {
    id: "mage_thunder",
    name: "雷电术",
    bookName: "雷电术技能书",
    profession: "法师",
    unlockLevel: 6,
    kind: "attack",
    manaCost: 26,
    cooldown: 2,
    basePower: 74,
    scaling: 1.4,
    duration: 0,
    description: "高空雷光垂落，电蛇缠绕目标周身，瞬间炸裂造成重创。",
  },
  {
    id: "mage_shield",
    name: "魔法盾",
    bookName: "魔法盾技能书",
    profession: "法师",
    unlockLevel: 12,
    kind: "shield",
    manaCost: 24,
    cooldown: 4,
    basePower: 22,
    scaling: 0,
    duration: 3,
    description: "凝聚魔力护盾，扭曲来袭冲击，将伤害导入虚空裂隙。",
  },
  {
    id: "mage_blizzard",
    name: "冰咆哮",
    bookName: "冰咆哮技能书",
    profession: "法师",
    unlockLevel: 18,
    kind: "attack",
    manaCost: 34,
    cooldown: 3,
    basePower: 96,
    scaling: 1.34,
    duration: 0,
    description: "极寒风暴席卷战场，冰刃翻卷切割，带来持续压迫。",
  },
  {
    id: "taoist_talisman",
    name: "灵魂火符",
    bookName: "灵魂火符技能书",
    profession: "道士",
    unlockLevel: 1,
    kind: "attack",
    manaCost: 15,
    cooldown: 1,
    basePower: 36,
    scaling: 1.16,
    duration: 0,
    description: "符纸燃起幽火，化作一线流光穿透护甲，专打内劲。",
  },
  {
    id: "taoist_heal",
    name: "治愈术",
    bookName: "治愈术技能书",
    profession: "道士",
    unlockLevel: 4,
    kind: "heal",
    manaCost: 18,
    cooldown: 2,
    basePower: 52,
    scaling: 0.8,
    duration: 0,
    description: "道印回旋，灵息汇聚，全身伤势在温润白光中加速愈合。",
  },
  {
    id: "taoist_poison",
    name: "施毒术",
    bookName: "施毒术技能书",
    profession: "道士",
    unlockLevel: 9,
    kind: "poison",
    manaCost: 20,
    cooldown: 3,
    basePower: 14,
    scaling: 0.6,
    duration: 4,
    description: "毒雾缠体，血气被缓缓侵蚀，越拖越痛苦。",
  },
  {
    id: "taoist_pet",
    name: "召唤神兽",
    bookName: "召唤神兽技能书",
    profession: "道士",
    unlockLevel: 16,
    kind: "summon",
    manaCost: 30,
    cooldown: 5,
    basePower: 18,
    scaling: 0.7,
    duration: 4,
    description: "法阵开启，神兽踏焰而出，持续撕咬并牵制敌人。",
  },
];

export const PROFESSION_SKILLS: Record<Profession, string[]> = {
  战士: ["warrior_attack_slash", "warrior_half_moon", "warrior_charge", "warrior_fire_sword"],
  法师: ["mage_fireball", "mage_thunder", "mage_shield", "mage_blizzard"],
  道士: ["taoist_talisman", "taoist_heal", "taoist_poison", "taoist_pet"],
};

export const MAPS: MapArea[] = [
  {
    id: "bq_wild",
    name: "比奇野外",
    minLevel: 1,
    maxLevel: 9,
    dropTier: 1,
    monsters: [
      {
        id: "bq_cat",
        name: "钉耙猫",
        level: 2,
        hp: 140,
        attack: 20,
        defense: 7,
        exp: 32,
        gold: 20,
        skillText: "钉耙猫挥舞利爪，猛扑而来。",
      },
      {
        id: "bq_orc",
        name: "半兽人",
        level: 4,
        hp: 190,
        attack: 26,
        defense: 10,
        exp: 48,
        gold: 34,
        skillText: "半兽人怒吼着抡起木棒，节奏凶悍。",
      },
      {
        id: "bq_spider",
        name: "毒蜘蛛",
        level: 6,
        hp: 230,
        attack: 31,
        defense: 12,
        exp: 58,
        gold: 42,
        skillText: "毒蜘蛛喷出腥绿毒液，气味刺鼻。",
      },
    ],
    bosses: [
      {
        id: "bq_boss_orc_king",
        name: "半兽统领",
        isBoss: true,
        level: 8,
        hp: 760,
        attack: 58,
        defense: 24,
        exp: 260,
        gold: 190,
        skillText: "半兽统领怒号震野，双斧连劈压得你难以喘息。",
      },
    ],
  },
  {
    id: "wm_temple",
    name: "沃玛寺庙",
    minLevel: 8,
    maxLevel: 16,
    dropTier: 2,
    monsters: [
      {
        id: "wm_fighter",
        name: "沃玛战士",
        level: 10,
        hp: 320,
        attack: 42,
        defense: 18,
        exp: 96,
        gold: 74,
        skillText: "沃玛战士挥动战斧，力道沉重。",
      },
      {
        id: "wm_hero",
        name: "沃玛勇士",
        level: 13,
        hp: 390,
        attack: 48,
        defense: 23,
        exp: 125,
        gold: 96,
        skillText: "沃玛勇士步步逼近，战斧带着破风声。",
      },
      {
        id: "wm_fire",
        name: "火焰沃玛",
        level: 15,
        hp: 430,
        attack: 55,
        defense: 25,
        exp: 150,
        gold: 112,
        skillText: "火焰沃玛周身冒火，热浪灼人。",
      },
    ],
    bosses: [
      {
        id: "wm_boss_master",
        name: "沃玛教主",
        isBoss: true,
        level: 16,
        hp: 1480,
        attack: 96,
        defense: 40,
        exp: 720,
        gold: 560,
        skillText: "沃玛教主挥出灼热雷焰，祭坛碎石飞溅而起。",
      },
    ],
  },
  {
    id: "zm_temple",
    name: "祖玛寺庙",
    minLevel: 15,
    maxLevel: 24,
    dropTier: 3,
    monsters: [
      {
        id: "zm_statue",
        name: "祖玛雕像",
        level: 17,
        hp: 560,
        attack: 68,
        defense: 30,
        exp: 220,
        gold: 150,
        skillText: "祖玛雕像石臂横扫，重击震地。",
      },
      {
        id: "zm_archer",
        name: "祖玛弓箭手",
        level: 19,
        hp: 530,
        attack: 74,
        defense: 28,
        exp: 238,
        gold: 164,
        skillText: "祖玛弓箭手连珠疾射，箭影密集。",
      },
      {
        id: "zm_guard",
        name: "祖玛卫士",
        level: 22,
        hp: 660,
        attack: 82,
        defense: 36,
        exp: 290,
        gold: 196,
        skillText: "祖玛卫士举锤下砸，地面裂开细纹。",
      },
    ],
    bosses: [
      {
        id: "zm_boss_leader",
        name: "祖玛教主",
        isBoss: true,
        level: 24,
        hp: 2360,
        attack: 148,
        defense: 62,
        exp: 1320,
        gold: 980,
        skillText: "祖玛教主擂动巨锤，祭坛之火喷薄，压迫感骤升。",
      },
    ],
  },
  {
    id: "cy_canyon",
    name: "赤月峡谷",
    minLevel: 23,
    maxLevel: 35,
    dropTier: 4,
    monsters: [
      {
        id: "cy_giant",
        name: "血巨人",
        level: 26,
        hp: 930,
        attack: 102,
        defense: 44,
        exp: 420,
        gold: 280,
        skillText: "血巨人咆哮着挥拳，空气都在颤动。",
      },
      {
        id: "cy_king",
        name: "双头金刚",
        level: 29,
        hp: 1050,
        attack: 112,
        defense: 51,
        exp: 470,
        gold: 330,
        skillText: "双头金刚双臂连击，压迫感十足。",
      },
      {
        id: "cy_demon",
        name: "赤月恶魔",
        level: 33,
        hp: 1220,
        attack: 124,
        defense: 58,
        exp: 560,
        gold: 390,
        skillText: "赤月恶魔释放猩红冲击，邪气翻涌。",
      },
    ],
    bosses: [
      {
        id: "cy_boss_demon_lord",
        name: "赤月魔君",
        isBoss: true,
        level: 36,
        hp: 3680,
        attack: 216,
        defense: 88,
        exp: 2380,
        gold: 1720,
        skillText: "赤月魔君张开血翼，暗红冲击横扫峡谷。",
      },
    ],
  },
];

export const SHOP_ITEMS: ShopItem[] = [
  {
    name: "金创药",
    price: 60,
    description: "恢复生命，自动战斗会在低血量时触发。",
  },
  {
    name: "魔法药",
    price: 75,
    description: "恢复魔法，保证技能循环不断档。",
  },
  {
    name: "修炼卷轴",
    price: 520,
    description: "选择一个技能，立即增加修炼值。",
  },
  {
    name: "强化石",
    price: 360,
    description: "强化装备时可提高成功率。",
  },
  {
    name: "幸运油",
    price: 880,
    description: "给武器抹油，提升幸运上限。",
  },
];

export const INITIAL_ITEMS: Record<ItemName, number> = {
  金创药: 8,
  魔法药: 6,
  修炼卷轴: 1,
  强化石: 1,
  幸运油: 0,
};
